In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [10]:
df = pd.read_csv('../data.csv')

df

C:\Users\shrij\AppData\Local\Temp\ipykernel_28316\56052805.py:1: DtypeWarning: Columns (0: label) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data.csv')

                                                     text label
0       Go until jurong point, crazy.. Available only ...   ham
1                           Ok lar... Joking wif u oni...   ham
2       Free entry in 2 a wkly comp to win FA Cup fina...  spam
3       U dun say so early hor... U c already then say...   ham
4       Nah I don't think he goes to usf, he lives aro...   ham
...                                                   ...   ...
560194  Subject: WINNER! Claim your reward\nHello,\n\n...     1
560195  Subject: Action items from sprint review\nHell...     0
560196  Subject: You received a secure message\nAttent...     1
560197  Subject: Holiday calendar and office closure\n...     0
560198  Subject: Pre-approved €99 credit\nFINAL ALERT:...     1

[560199 rows x 2 columns]

In [11]:
df_training, df_testing = train_test_split(df, test_size = 0.2, random_state = 42)

In [12]:
df_training

                                                     text label
477703  Subject: Minutes: Sales standup\nHi Riya,\n\nY...     0
7236    Subject: fw : winston  debbie ,  this is an up...     0
322923  online pharmacy visit our online store and sav...     2
172995  http www spcm org journal spip php articleesca...     0
131514  i have been having a weird non fatal problem l...     0
...                                                   ...   ...
110268  as a dependable e supplier we know the reason ...     2
259178  cnn alerts physic_1950rsvpscom cnn alerts cust...     1
365838  good morning ,\nwe we offer latest oem package...     2
131932  compañía americana esta solicitando distribuid...     2
121958  work from home resources we are desperately ne...     2

[448159 rows x 2 columns]

In [13]:
df_testing

                                                     text label
36809   effective july 1 avails , beverly beaty will b...     0
401622  john apologize tone e mail hope agree e mail c...     0
362479  fax email mstyles favorites tagged any type of...     2
497932  Subject: Your parcel is waiting (ID 633999)\nI...     1
167222  don't waste the opportunity  anatrim  the ve...     2
...                                                   ...   ...
53936   i will be out of the office thursday july 12 t...     0
477332  Subject: Exclusive deal on music subscription ...     1
43864   third order nanotechnologies achieves major te...     1
198529  hi paliourg ,\nwe are your convenient , safe a...     2
514861  Subject: Release notes v2.4.4\nHi Vik,\n\nRemi...     0

[112040 rows x 2 columns]

In [14]:
print('Training data:')
print(df_training.columns)
print()
print('Testing data:')
print(df_testing.columns)

Training data:
Index(['text', 'label'], dtype='str')

Testing data:
Index(['text', 'label'], dtype='str')

In [15]:
print(df_training['label'].value_counts())
print(df_testing['label'].value_counts())

label
0                                                                                               121764
0                                                                                                88284
2                                                                                                73335
1                                                                                                67086
2                                                                                                49891
1                                                                                                43312
ham                                                                                               3887
spam                                                                                               595
 its termination would not  have such a phenomenal impact on the power situation .  however          1
 mr suresh prabhu                                                                                    1
{"mode":"full"                                                                                       1
Name: count, dtype: int64
label
0       30396
0       21907
2       18357
1       16834
2       12565
1       10891
ham       938
spam      152
Name: count, dtype: int64

In [16]:
df_training.to_csv('../training_data.csv', index = False)
df_testing.to_csv('../testing_data.csv', index = False)

In [1]:
!jupyter nbconvert --to script dataset_split.ipynb

[NbConvertApp] Converting notebook dataset_split.ipynb to script
[NbConvertApp] Writing 662 bytes to dataset_split.py